### ISSUE TITLE
Failing optimistic registry tests

### ISSUE THREAD

**Issue by samajammin** [ethereum/clrfund#217]
Looks like our recent changes (#214 & #71) broke a few tests:

```
161 passing (3m)
  6 failing

  1) Optimistic recipient registry
       managing recipients
         allows anyone to submit registration request:
     Uncaught RuntimeError: abort(AssertionError: Expected "RequestSubmitted" event to have 5 argument(s), but it has 6). Build with -s ASSERTIONS=1 for more info.
      at process.abort (node_modules/@ethereum-waffle/compiler/node_modules/solc/soljson.js:1:14382)
      at process.emit (node:events:378:20)
      at process.emit (node_modules/source-map-support/source-map-support.js:485:21)
      at process.emit (node_modules/ganache-core/node_modules/source-map-support/source-map-support.js:465:21)
      at emit (node:internal/process/promises:135:22)
      at processPromiseRejections (node:internal/process/promises:241:25)
      at processTicksAndRejections (node:internal/process/task_queues:95:32)
      at runNextTicks (node:internal/process/task_queues:63:3)
      at listOnTimeout (node:internal/timers:526:9)
      at processTimers (node:internal/timers:500:7)

  2) Optimistic recipient registry
       managing recipients
         allows anyone to submit registration request:
     Error: done() called multiple times in test <Optimistic recipient registry managing recipients allows anyone to submit registration request> of file /Users/samrichards/code/ef/clrfund/contracts/tests/recipientRegistry.ts
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:94:5)

  3) Optimistic recipient registry
       managing recipients
         allows anyone to submit removal request:
     Error: VM Exception while processing transaction: revert Ownable: caller is not the owner
      at OptimisticRecipientRegistry.onlyOwner (@openzeppelin/contracts/access/Ownable.sol:43)
      at OptimisticRecipientRegistry.removeRecipient (contracts/recipientRegistry/OptimisticRecipientRegistry.sol:127)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:94:5)
      at EthModule._sendTransactionAndReturnHash (node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:1332:9)
      at HardhatNetworkProvider.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:102:18)
      at WaffleMockProviderAdapter.send (node_modules/@nomiclabs/hardhat-waffle/src/waffle-provider-adapter.ts:31:20)

  4) Optimistic recipient registry
       managing recipients
         should not accept removal request with incorrect deposit size:

      AssertionError: Expected transaction to be reverted
      + expected - actual

      -Transaction NOT reverted.
      +Transaction reverted.



  5) Optimistic recipient registry
       managing recipients
         allows owner to challenge removal request:
     Error: VM Exception while processing transaction: revert Ownable: caller is not the owner
      at OptimisticRecipientRegistry.onlyOwner (@openzeppelin/contracts/access/Ownable.sol:43)
      at OptimisticRecipientRegistry.removeRecipient (contracts/recipientRegistry/OptimisticRecipientRegistry.sol:127)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:94:5)
      at EthModule._sendTransactionAndReturnHash (node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:1332:9)
      at HardhatNetworkProvider.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:102:18)
      at WaffleMockProviderAdapter.send (node_modules/@nomiclabs/hardhat-waffle/src/waffle-provider-adapter.ts:31:20)

  6) Optimistic recipient registry
       managing recipients
         allows anyone to execute unchallenged removal request:
     Error: VM Exception while processing transaction: revert Ownable: caller is not the owner
      at OptimisticRecipientRegistry.onlyOwner (@openzeppelin/contracts/access/Ownable.sol:43)
      at OptimisticRecipientRegistry.removeRecipient (contracts/recipientRegistry/OptimisticRecipientRegistry.sol:127)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:94:5)
      at EthModule._sendTransactionAndReturnHash (node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:1332:9)
      at HardhatNetworkProvider.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:102:18)
      at WaffleMockProviderAdapter.send (node_modules/@nomiclabs/hardhat-waffle/src/waffle-provider-adapter.ts:31:20)

```

**Comment by samajammin** [comment]
@pettinarip mind taking a look at this? Happy to pair on this but I think the changes should be fairly straightforward. Thanks!
